### ISSUE TITLE
Error with verifySignature() on NextJS 14 pages router

### ISSUE THREAD

**Issue by AndreyMay** [upstash/qstash-js#105]
On latest version (v2.5.4) started getting the following error when using `verifySignature(handler)` on pages router:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '.../node_modules/next/server' imported from .../node_modules/@upstash/qstash/nextjs.mjs
app:dev: [1] Did you mean to import "next/server.js"?
```

No error on v2.5.0

**Comment by AndreyMay** [comment]
looks like the same issue in the last comments https://github.com/upstash/qstash-js/issues/44

**Comment by ogzhanolguncu** [comment]
Should be fixed here: https://github.com/upstash/qstash-js/releases/tag/v2.5.5.

**Comment by fahreddinozcan** [comment]
Now that it's fixed, I'm closing this issue.
