### ISSUE TITLE
Unable to Batch to a Queue

### ISSUE THREAD

**Issue by benwilhelm** [upstash/qstash-js#134]
The [QStash documentation](https://upstash.com/docs/qstash/features/batch#batching-messages-with-queue) says that when calling `client.batchJSON`, I can specify a `queueName` to route messages to my queues. Unfortunately, that doesn't seem to be the case. Posting a batch in the following format does not send my messages to any queues:

```javascript
client.batchJSON([
 {
    url: 'https://my-cool-site.com/my-route',
    queueName: 'my-queue',
    body: { /*...a json object...*/ }
  },
  {
    url: 'https://my-cool-site.com/my-route',
    queueName: 'my-queue',
    body: { /*...another json object...*/ }
  }
])
```
Screenshot of results:

![Screenshot 2024-07-25 at 2 36 30 PM](https://github.com/user-attachments/assets/72ea8d41-c5c2-47f8-96d9-16dd463e6e53)

I am able to post individual messages to my queues using `queue.enqueueJSON(...)`, but it doesn't seem that I can batch messages using the queue object. 

Help? Please and thank you :)

**Comment by CahidArda** [comment]
Hey @benwilhelm, I tried the same code but it worked in my case.

Which qstash-js version are you using? Also, do you have `await` in your code? You should await for the batch request to finish:
```ts
// await:
await client.batchJSON([
 {
    url: 'https://my-cool-site.com/my-route',
    queueName: 'my-queue',
    body: { /*...a json object...*/ }
  },
  {
    url: 'https://my-cool-site.com/my-route',
    queueName: 'my-queue',
    body: { /*...another json object...*/ }
  }
])
```

**Comment by benwilhelm** [comment]
Ah, it was a version issue. I was pinned at 2.5.0, and updating to latest fixed it. Thanks!
