### ISSUE TITLE
Build failing due to env vars not present during vercel deployment

### ISSUE THREAD

**Issue by deepso7** [upstash/qstash-js#145]
using `export const POST = verifySignatureAppRouter(...)` in nextjs app router route 
error is thrown when vercel is building the app at the time of deployments because env vars are not present 
though env vars are present in vercel env.

Error: `@acme/nextjs:build: Error: currentSigningKey is required, either in the config or as env variable QSTASH_CURRENT_SIGNING_KEY`

<img width="1243" alt="image" src="https://github.com/user-attachments/assets/9dbf7d20-0502-4fa4-ba57-ea4cbf015686">

**Comment by ogzhanolguncu** [comment]
```
QSTASH_TOKEN="xxxxx"

QSTASH_CURRENT_SIGNING_KEY="xxx"
QSTASH_NEXT_SIGNING_KEY="xxx"
```

Do they look like this? If not error is expected, yeah.

**Comment by deepso7** [comment]
> ```
> QSTASH_TOKEN="xxxxx"
> 
> QSTASH_CURRENT_SIGNING_KEY="xxx"
> QSTASH_NEXT_SIGNING_KEY="xxx"
> ```
> 
> Do they look like this? If not error is expected, yeah.

yess they look like this only
but for me seems like vercel is not loading the env at the time of build

**Comment by ogzhanolguncu** [comment]
We are looking into it

**Comment by deepso7** [comment]
> We are looking into it

found one related issue, https://github.com/vercel/next.js/discussions/38164

**Comment by gablabelle** [comment]
FYI, I had the same issue after upgrading to turborepo 2 yesterday. Then I realized that the `QSTASH_CURRENT_SIGNING_KEY` environment variable was simply missing from the `globalEnv` array in the turbo.json config file.

Adding it there, fixed the issue for me. Maybe this will help someone. ;-)

**Comment by deepso7** [comment]
> FYI, I had the same issue after upgrading to turborepo 2 yesterday. Then I realized that the `QSTASH_CURRENT_SIGNING_KEY` environment variable was simply missing from the `globalEnv` array in the turbo.json config file.
> 
> Adding it there, fixed the issue for me. Maybe this will help someone. ;-)

Thanks for pointing that out, @gablabelle. I also forgot to add them to globalEnv. After adding them, the builds are working perfectly fine.
