### ISSUE TITLE
SvelteKit Support

### ISSUE THREAD

**Issue by Spikeysanju** [upstash/qstash-js#20]
Since I have been using the QStash library with Next JS and I find it amazing, I am wondering if Upstash has any plans to make it compatible with SvelteKit and its stand alone API endpoints. I am aware that a lot of work would need to be done, such as verifying JWT tokens, but SvelteKit is only 5 issues away from its 1.0 stable release. Any help would be greatly appreciated. Thank you in advance.

**Comment by chronark** [comment]
I have never used svelte, but you could use the `Receiver` manually, right?
```ts
import { Receiver } from "@upstash/qstash"


const receiver = new Receiver({
  currentSigningKey: "...",
  nextSigningKey: "...",
});

const isValid = await receiver.verify({
  signature: "...",
  body: "...",
})
  ```
  
What are the issues you see with using this in svelte?
  
First class support for svelte sounds nice, I just don't really have much capacity right now and also don't know svelte at all.
But I would love to get contributions for this!  <3

**Comment by CahidArda** [comment]
Svelte was added to upstash/qstash. You can learn more from the examples

https://github.com/upstash/qstash-js/tree/main/examples/svelte
https://github.com/upstash/qstash-js/tree/main/examples/workflow/sveltekit
