### ISSUE TITLE
Question: would the queue process in sequence

### ISSUE THREAD

**Issue by qhuynhvhslab** [upstash/qstash-js#32]
Hi,

I am considering using qstash and just wondering if the message published into queue would be processed in sequence, and the next message would only be processed only when the first message is finished processing and removed from queue, and not during the first message is not removed yet.

Would there be option to specify something like this when we create a new topic.

**Comment by chronark** [comment]
Hey, currently there is no concurrency limit. But I'm working on providing such a feature.

**Comment by elie222** [comment]
> Hey, currently there is no concurrency limit. But I'm working on providing such a feature.

Any idea what the timeline for that is? Would be a great feature to have. Very helpful when working with external APIs to avoid getting rate limited.

**Comment by chronark** [comment]
With v2 we've laid the foundation to make this possible, but we got other things in the pipeline first, so not likely to be in the next 1-2 months

**Comment by sitoftonic** [comment]
Same here. What is the estimated time for this feature?

**Comment by CahidArda** [comment]
This feature was added. See the announcement for more details. https://upstash.com/blog/qstash-fifo-parallelism
