### ISSUE TITLE
Published package.json version string contains 'v' prefix

### ISSUE THREAD

**Issue by hmarr** [upstash/qstash-js#74]
While I think it is technically allowed, it seems uncommon. Here's a project I'm working on with lots of dependencies—upstash is the only package with the prefix:

```
$ $ find node_modules -name package.json | wc -l
    2720
$ grep -R --include package.json '"version": "v' node_modules | wc -l
       1
$ grep -R --include package.json '"version": "v' node_modules
node_modules/@upstash/qstash/package.json:  "version": "v2.2.0",
```

It appears to be confusing the `npm outdated` command:

```
$ npm outdated
Package          Current  Wanted  Latest  Location                      Depended by
@upstash/qstash   v2.2.0   2.2.0   2.2.0  node_modules/@upstash/qstash  ---
```

I think it's happening because your release script sets the version based on the release ref name:

https://github.com/upstash/sdk-qstash-ts/blob/4b93fa1dc5b60616de78257f6c2f3bd324c5145e/.github/workflows/release.yml#L16-L17

Then substitutes that version directly into the package.json:

https://github.com/upstash/sdk-qstash-ts/blob/4b93fa1dc5b60616de78257f6c2f3bd324c5145e/.github/workflows/release.yml#L44-L45

So it should be an easy fix!

**Comment by ogzhanolguncu** [comment]
I understand the issue, but the funny thing is outdated doesn't show up for me when im using the latest version. Unless you specifically install `@upstash/qstash@v2.2.0`, because latest will point to `@upstash/qstash@latest` -> `@upstash/qstash@2.2.0`. By the way I still agree we can omit the `v`, but this issue shouldn't affect you. We do this for all the repos we have(convention started long time before I joined).

**Comment by ogzhanolguncu** [comment]
Ahhh, you know what maybe thats on npm. I mostly use pnpm or bun nowadays let me test with npm and get back to you.

**Comment by ogzhanolguncu** [comment]
```
>  npm remove @upstash/qstash && npm install @upstash/qstash@latest  && npm outdated

removed 2 packages, and audited 6 packages in 527ms

found 0 vulnerabilities

added 2 packages, and audited 8 packages in 2s

1 package is looking for funding
  run `npm fund` for details
```

Well, it didn't reproduce on my end.
